_daylight-sh ()
{
	local curr=$2
	local last=$3

	local mainCmds=(\
		activate-flask-app \
		activate-svc \
		activate-vm \
		add-container-user \
		add-ssh-to-container \
		add-superuser \
		add-user \
		add-user-to-idmap \
		add-user-to-shadow-ids \
		cat-conf-script \
		create-flask-app \
		create-github-user-access-token \
		create-home-filesystem \
		create-loopback \
		create-lxd-user-data \
		create-pubbo-service \
		create-publish-image-service \
		create-service-from-dist-script \
		create-static-website \
		create-temp-file \
		create-temp-folder \
		daylight \
		delete-lxd-instance \
		download-app \
		download-daylight \
		download-dist \
		download-dylt \
		download-flask-app \
		download-flask-service \
		download-public-key \
		download-shr-tarball \
		download-svc \
		download-to-temp-dir \
		download-vm \
		ec \
		edit-daylight \
		error \
		error_log \
		etcd-download-latest \
		etcd-download-release \
		etcd-gen-join-script \
		etcd-gen-run-script \
		etcd-gen-unit-file \
		etcd-get-download-url \
		etcd-get-latest-version \
		etcd-install-latest \
		etcd-install-release \
		etcd-install-service \
		etcd-setup-data-dir \
		events \
		gen-nginx-flask \
		gen-nginx-static \
		generate-unit-file \
		get-bucket \
		get-container-ip \
		get-image-base \
		get-image-name \
		get-image-repo \
		get-service-environment-file \
		get-service-exec-start \
		get-service-file-value \
		get-service-working-directory \
		getVmName \
		github-create-user-access-token \
		github-curl \
		github-curl-post \
		github-download-latest-release \
		github-get-app-client-id \
		github-get-app-data \
		github-get-app-info \
		github-get-latest-release-tag \
		github-get-release-data \
		github-get-release-name-list \
		github-get-release-package-data \
		github-get-release-package-info \
		github-get-releases-url-path \
		github-install-latest-release \
		github-test-repo \
		github-test-repo-with-auth \
		go-service-gen-nginx-domain-file \
		go-service-gen-run-script \
		go-service-gen-stop-script \
		go-service-gen-unit-file \
		go-service-install \
		go-service-uninstall \
		hello \
		http \
		incus-create-ssh-profile \
		incus-create-www-profile \
		incus-pull-file \
		incus-push-file \
		incus-remove-file \
		init-lxd \
		init-nginx \
		install-app \
		install-awscli \
		install-dylt \
		install-etcd \
		install-flask-app \
		install-fresh-daylight-svc \
		install-gnome-keyring \
		install-latest-httpie \
		install-mssql-tools \
		install-pubbo \
		install-public-key \
		install-python \
		install-service \
		install-service-from-command \
		install-service-from-script \
		install-shellscript-part-handlers \
		install-shr-token \
		install-svc \
		install-venv \
		install-vm \
		list-apps \
		list-conf-scripts \
		list-funcs \
		list-git-repos \
		list-public-keys \
		list-services \
		list-shr-entries \
		list-vms \
		log \
		lxd-dump-id-map \
		lxd-instance-exists \
		lxd-set-id-map \
		lxd-share-folder \
		mkdir \
		modules-enabled \
		prep-filesystem \
		prep-service \
		pull-app \
		pull-daylight \
		pull-flask-app \
		pull-git-repo \
		pull-image \
		pull-ssh-tarball \
		pull-svc \
		pull-vm \
		pull-webapp \
		pullAppInfo \
		push-app \
		push-daylight \
		push-flask-app \
		push-svc \
		push-webapp \
		replace-nginx-conf \
		restart-nginx \
		run-conf-script \
		run-service \
		setup-domain \
		socketFolder \
		source-daylight \
		source-service-environment-file \
		start-indexed-service \
		start-service \
		stream \
		streams \
		sys-start \
		uninstall-etcd \
		untar-to-temp-folder \
		update-and-restart \
		watch-daylight-gen-run-script \
		watch-daylight-gen-unit-file \
		watch-daylight-install-service \
		worker_processes \
		www-data \
		yesno \
	)

    # Trim everything up to + including the first slash
	local lastCmd=${last##*/}
	case "$lastCmd" in
		daylight.sh)
			# Typical mapfile + comgen -W idiom
			mapfile -t COMPREPLY < <(compgen -W "${mainCmds[*]}" -- "$curr")
			;;
	esac
}

complete -F _daylight-sh daylight.sh
