name: Nightly release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag
        id: tag
        run: echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Generate github-utils.sh
        run: ./extract-github-funcs.sh > github-utils.sh
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.DATE }}
          target_commitish: main
          files: github-utils.sh
          body: "Nightly release — ${{ steps.tag.outputs.DATE }}"
